version: "3.9"
services:
  db:
    image: postgres:15
    container_name: osaka_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-osaka_menesu}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  meili:
    image: getmeili/meilisearch:v1.7
    container_name: osaka_meili
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-dev_meili_master_key}
    ports:
      - "7700:7700"
    command: ["meilisearch", "--http-addr", "0.0.0.0:7700"]

  redis:
    image: redis:7-alpine
    container_name: osaka_redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: ./services/api
    container_name: osaka_api
    env_file:
      - ./.env
    environment:
      RATE_LIMIT_REDIS_ERROR_COOLDOWN: ${RATE_LIMIT_REDIS_ERROR_COOLDOWN:-30}
    volumes:
      - ./services/api:/app
    depends_on:
      - db
      - meili
      - redis
    ports:
      - "8000:8000"
    command: ["bash", "start.sh"]

  web:
    build: ./apps/web
    container_name: osaka_web
    env_file:
      - ./.env
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    depends_on:
      - api

volumes:
  db_data: {}
  redis_data: {}
