---
version: "3"

includes:
  core: tasks/core.yml
  venv: tasks/venv.yml
  cursor: tasks/cursor.yml
  tests: tasks/tests.yml
  flow: tasks/flow.yml
  next: tasks/next.yml
  parallel: tasks/parallel.yml
  debug: tasks/debug.yml
  check: tasks/check.yml
  run12: tasks/run12.yml
  fixgen: tasks/fix_generate.yml
  fixcdp: tasks/fix_cdp.yml
  fixpatch: tasks/fix_patch.yml
  workflow: tasks/workflow.yml
  validate: tasks/validate.yml
  ci: tasks/ci.yml
  after: tasks/after_ci.yml
