---
version: "3"

includes:
  core: ./core.yml        # COUNT / LOG_DIR 変数
  debug: ./debug.yml      # cpu / log / log:ls / restart など

tasks:
  #──────────────────────────────────────────────
  # 🟢  現在稼働中の cursor agent 数を表示
  #──────────────────────────────────────────────
  agents:
    desc: "pgrep で cursor agent 件数をカウント"
    cmds:
      - |
        if command -v pgrep >/dev/null 2>&1; then
          CNT=$(pgrep -fl "cursor.*agent" | wc -l | tr -d ' ')
        else
          CNT=$(ps aux | grep "cursor.*agent" | grep -v grep | wc -l | tr -d ' ')
        fi
        echo "👀  running cursor agent: ${CNT} 件"

  #──────────────────────────────────────────────
  # 🟢  現在の CI (validate-and-test) の最新ステータスを 1 行表示
  #──────────────────────────────────────────────
  ci:
    desc: "GitHub Actions validate-and-test ⤵︎ status (skip if gh 未認証)"
    cmds:
      - |
        if ! gh auth status >/dev/null 2>&1; then
          echo "🔒 gh 未認証 → CI チェックをスキップ"; exit 0; fi
        SHA=$(git rev-parse HEAD)
        WF="validate-and-test"
        gh run list -c "$WF" -b "$SHA" --limit 1 --json status,conclusion -q \
          '"🛠  CI: \(.[] .status) / \(.[] .conclusion)"' \
          || echo "🛠  CI: run not found"

  #──────────────────────────────────────────────
  # 🟢  共有 venv サイズと SSD 空き容量表示
  #──────────────────────────────────────────────
  disk:
    desc: "du で shared venv & df で空き容量"
    cmds:
      - du -sh {{.SHARED_VENV}} || echo "shared venv 未作成"
      - df -h .

  #──────────────────────────────────────────────
  # 🏁  オールインワン
  #──────────────────────────────────────────────
  all:
    desc: "CPU▶︎ログ一覧▶︎agent 件数▶︎CI▶︎disk を一括表示"
    cmds:
      - task debug:cpu
      - task debug:log:ls
      - task check:agents
      - task check:ci
      - task check:disk 