---
version: "3"

includes:
  core: ./core.yml        # COUNT / WT_DIR など共通変数

tasks:
  # ----------------------------------------------------------------------------
  # ① 変更をコミットして main へ push
  #     task ci:commit-push
  # ----------------------------------------------------------------------------
  commit-push:
    desc: "stage → commit → push (main)"
    cmds:
      - git add -A
      - |
          if ! git diff --cached --quiet; then
            git commit -m "ci: auto-push"
          else
            echo "🟢 nothing to commit (skip commit)"
          fi
      - git push -u origin HEAD

  # ----------------------------------------------------------------------------
  # ② 直近コミットの GitHub Actions をウォッチして結果が出るまで待機
  #     task ci:ci-wait
  # ----------------------------------------------------------------------------
  ci-wait:
    desc: "wait GitHub Actions result for HEAD commit"
    deps: [commit-push]
    silent: true
    cmds:
      - |
          SHA=$(git rev-parse HEAD)
          echo "🔍 waiting CI for $SHA ..."
          while :; do
            STATUS=$(gh run list -c "$SHA" -L 1 --json status -q '.[0].status' 2>/dev/null || echo none)
            RESULT=$(gh run list -c "$SHA" -L 1 --json conclusion -q '.[0].conclusion' 2>/dev/null || echo none)

            if [ "$STATUS" = none ]; then
              echo "🔄 run not found yet"; sleep 20; continue
            fi
            if [ "$STATUS" != completed ]; then
              echo "⏳ CI $STATUS…"; sleep 20; continue
            fi
            if [ "$RESULT" = success ]; then
              echo "✅ CI success"; break
            fi

            echo "❌ CI $RESULT"; exit 1
          done

  # ----------------------------------------------------------------------------
  # ③ ブラウザで最新 CI Run を直接開く
  #     task ci:screen
  # ----------------------------------------------------------------------------
  screen:
    desc: "open latest CI run in browser"
    cmds:
      - |
          SHA=$(git rev-parse HEAD)
          URL=$(gh run list -c "$SHA" -L 1 --json url -q '.[0].url')
          if [ -n "$URL" ] && [ "$URL" != "null" ]; then
            echo "🌐 Opening $URL"
            open "$URL"
          else
            echo "⚠️  No CI run found for $SHA"; exit 1
          fi 