---
version: "3"

vars:
  COUNT: 12                      # fixed number of worktrees
  WT_DIR: "../ai-task"            # worktree directory prefix
  LOG_DIR: "../../logs"           # log directory used by cursor tasks
  CURSOR_BIN: "$(command -v cursor-cli || command -v cursor)"
  SHARED_VENV: "../shared_venv"             # shared virtual environment path
  CFG: "../kakeru/agents.yaml"    # default Cursor agent config path

# Environment variables applied project-wide
env:
  VIRTUAL_ENV: "{{.SHARED_VENV}}"
  # Prepend shared venv's bin so `python`, `pytest`, etc. resolve
  PATH: "{{.SHARED_VENV}}/bin:${PATH}"

tasks:
  _core:noop:
    cmds: [echo core OK]
