# yamllint disable rule:line-length
---
version: "3"

tasks:
  _cursor:noop:
    cmds: [echo cursor OK]
  auto:
    desc: "Ensure official 'cursor' CLI is in PATH (macOS)"
    cmds:
      - |
        set -e
        if command -v cursor >/dev/null 2>&1; then
          echo "✅ cursor CLI already present -> $(which cursor)"; exit 0; fi

        # 1) GUI が入っていれば直接シェルコマンドを登録
        if [ -e /Applications/Cursor.app ]; then
          echo "⚙️  Trying --install-shell-command flag …"
          open -a "/Applications/Cursor.app" --args --install-shell-command || true
          sleep 2
        fi

        # 2) AppleScript フォールバック
        if ! command -v cursor >/dev/null 2>&1 && [ -e /Applications/Cursor.app ]; then
          echo "⚙️  AppleScript fallback …"
          osascript \
            -e 'tell application "Cursor" to activate' \
            -e 'delay 1' \
            -e 'tell application "System Events" to keystroke "P" using {command down, shift down}' \
            -e 'delay 0.3' \
            -e 'tell application "System Events" to keystroke "Shell command: Install ""cursor"" command"' \
            -e 'delay 0.3' \
            -e 'tell application "System Events" to key code 36'
          sleep 2
        fi

        # 3) 最終手段: Homebrew で GUI 本体を入れて実行
        if ! command -v cursor >/dev/null 2>&1; then
          echo "🔧 Installing Cursor GUI via Homebrew…"
          brew install --cask cursor || true
          open -a "/Applications/Cursor.app" --args --install-shell-command || true
          sleep 2
        fi

        if command -v cursor >/dev/null 2>&1; then
          echo "🎉 cursor CLI ready -> $(which cursor)";
        else
          echo "❌ Failed to install cursor CLI"; exit 1;
        fi
    silent: false
    status:
      - '[ ! -x "$(command -v cursor)" ]'
