---
version: "3"

includes:
  core: ./core.yml

tasks:
  #──────────────────────────────────────────────
  # 🔍  CPU 使用率 / Load Average を表示
  #──────────────────────────────────────────────
  cpu:
    desc: "show current CPU load (uptime & top)"
    cmds:
      - uptime
      - |
        if command -v top >/dev/null 2>&1; then
          if [[ "$(uname)" == "Darwin" ]]; then
            top -l 1 | head -n 10 || true
          else
            top -b -n 1 | head -n 10 || true
          fi
        fi

  #──────────────────────────────────────────────
  # 📄  ログディレクトリの一覧表示
  #──────────────────────────────────────────────
  log:ls:
    desc: "list recent agent log files in {{.LOG_DIR}}"
    cmds:
      - ls -lh {{.LOG_DIR}} 2>/dev/null | tail -n 20 || echo "(no log files)"

  #──────────────────────────────────────────────
  # 🔄  cursor agent プロセスをすべて再起動（stop only here）
  #──────────────────────────────────────────────
  restart:
    desc: "kill all running cursor agent processes"
    cmds:
      - |
        echo "🛑 stopping cursor agents …"
        if command -v pkill >/dev/null 2>&1; then
          pkill -f "cursor.*agent" || true
        else
          # fallback using ps + kill
          ps aux | grep "cursor.*agent" | grep -v grep | awk '{print $2}' | xargs -r kill -9 || true
        fi
      - echo "✅  agents stopped"

  #──────────────────────────────────────────────
  # 🧪 失敗テストを素早く特定するユーティリティ
  #──────────────────────────────────────────────
  tests:first-fail:
    desc: "pytest -x で 1 件目の失敗を表示 (ai-task-1)"
    cmds:
      - |
        cd ../ai-task-1
        if [ -f .venv/bin/activate ]; then source .venv/bin/activate; fi
        echo "▶︎ showing first failing test in ai-task-1"
        pytest -q tests -x

  tests:fail:
    desc: "pytest -x in ai-task-<N> (default 1)"
    vars:
      IDX: "{{.CLI_ARGS | default `1`}}"
    cmds:
      - |
        cd ../ai-task-{{.IDX}}
        if [ -f .venv/bin/activate ]; then source .venv/bin/activate; fi
        echo "▶︎ ai-task-{{.IDX}} first failing test"
        pytest -q tests -x

  log:tail:
    desc: "tail -f logs/run_<N>.log (default 1)"
    vars:
      N: "{{.CLI_ARGS | default `1`}}"
    cmds:
      - tail -f ../../logs/run_{{.N}}.log 