# tasks/fix_validate.yaml
# yamllint disable rule:line-length
---
- task: fix_validate_and_commit
  goal: |
    1. tasks/validate.yml の validate-and-test タスクを修正して
       --dry-run 部分が正しいサブタスク名を参照するようにする
    2. pytest が未インストールなら自動で入れる
    3. validate-and-test を実行して緑になることを確認
    4. ブランチ作成 → コミット → プッシュ
  files:
    - path: tasks/validate.yml
      edits:
        # ❶ "task --dry validate:commit-task-split" が存在しないため置換
        - find: "task --dry validate:commit-task-split"
          replace: "task commit-task-split --dry"
        # ❷ pytest 自動インストール用コマンドを追記
        - after: "- yamllint tasks/"
          insert: |
            - |
              if ! python - <<'PY'
              import importlib.util, sys
              sys.exit(importlib.util.find_spec("pytest") is None)
              PY
              then
                echo "⚙️  Installing pytest ..."
                pip install -U pytest
              fi
  commands:
    # ❸ 修正後の検証フェーズ
    - run: "task validate:validate-and-test"  # タスク一覧→YAML lint→dry-run→pytest
    # ❹ Git 操作（ブランチが無ければ作成）
    - run: "git switch -c refactor/task-split || git switch refactor/task-split"
    - run: git add tasks/validate.yml
    - run: "git commit -m 'fix: repair validate-and-test task and add pytest auto-install'"
    - run: "git push -u origin HEAD"
