---
version: "3"

includes:
  core: ./core.yml      # COUNT, WT_DIR など
  tests: ./tests.yml    # link や validate に依存
  parallel: ./parallel.yml

# モジュール配置＆パイプライン再実行用

tasks:
  #──────────────────────────────────────────────
  # ① generate_recruit_posts.py を適切な場所へコピー
  #──────────────────────────────────────────────
  move-module:
    desc: "copy generate_recruit_posts.py → bot/services/twitter_client/"
    cmds:
      - |
        SRC="generate_recruit_posts.py"
        DEST="bot/services/twitter_client/generate_recruit_posts.py"
        if [ -f "$DEST" ]; then
          echo "✅ $DEST 既に存在 — skip"
        else
          if [ -f "$SRC" ]; then
            mkdir -p "$(dirname "$DEST")"
            cp -p "$SRC" "$DEST"
            echo "🔧 copied $SRC → $DEST"
          else
            echo "⚠️  $SRC が見つかりません。場所を確認してください。" && exit 1
          fi
        fi

  #──────────────────────────────────────────────
  # ② 12 並列パイプライン再実行
  #──────────────────────────────────────────────
  run12:
    desc: "fix module → tests link → validate → parallel pipeline"
    deps:
      - move-module
      - tests:link            # main/tests を各 worktree へリンク
      - tests:validate-linked # pytest dry-run
      - parallel:run
      - parallel:pick
    cmds:
      - echo "🎉  generate_recruit_posts import fix & pipeline complete" 