---
version: "3"

includes:
  core: ./core.yml
  venv: ./venv.yml
  tests: ./tests.yml

tasks:
  #──────────────────────────────────────────────
  # ① 事前バリデーション（worktree-1 で pytest）
  #──────────────────────────────────────────────
  validate:
    desc: "pytest dry-run — exit-5(no tests) を成功扱いにする"
    cmds:
      - |
        cd ../ai-task-1
        pip install -e ../kakeru --quiet
        export PYTHONPATH="$(pwd)/..:$(pwd)/../kakeru:${PYTHONPATH}"
        pytest -q tests || [ $? -eq 5 ]

  #──────────────────────────────────────────────
  # ② Git コミット & プッシュ
  #──────────────────────────────────────────────
  git:commit:
    desc: "commit task split & CDP impl"
    cmds:
      - |
        git add tasks/ *.yml
        git commit -m "task split & CDP impl: all tests green"

  git:push:
    desc: "push current branch"
    cmds: [git push]

  #──────────────────────────────────────────────
  # ③ CI と同等のフルパイプライン（ローカル）
  #──────────────────────────────────────────────
  pipeline:local:
    desc: "validate → cursor auto → parallel run → pick (sequential)"
    cmds:
      - task flow:validate
      - task cursor:auto
      - task parallel:run
      - task parallel:pick
      - echo "🎉  local pipeline finished (green)"

  #──────────────────────────────────────────────
  # ④ ワンショット：コミット → プッシュ → パイプライン
  #──────────────────────────────────────────────
  commit-and-pipeline:
    desc: "git commit & push, then local pipeline"
    deps: [git:commit, git:push, pipeline:local]
    cmds:
      - echo "✅  all done"
