---
# ────────────────────────────────────────────────
# tasks/ghcr.yml  ― GHCR イメージ操作ユーティリティ
#   ▸ ghcr:list          : GHCR 上のイメージ一覧を取得
#   ▸ ghcr:pull-latest   : latest を pull して smoke-test
#   ▸ ghcr:prune-obsolete: 保持日数を超えたタグを自動削除
# ────────────────────────────────────────────────
version: "3"

includes:
  core: ./core.yml        # 既存の COUNT / WT_DIR など
  tests: ./tests.yml
  parallel: ./parallel.yml

vars:
  GHCR_USER:  yusaku0324
  GHCR_REPO:  kakeru
  RETAIN_DAYS: 14         # 日数を変えたい場合はここだけ

tasks:
  list:
    desc: "一覧取得 – gh api で GHCR のタグ情報を表示"
    cmds:
      - |
        gh api -H "Accept: application/vnd.github+json" \
          /users/{{.GHCR_USER}}/packages/container/{{.GHCR_REPO}}/versions \
          | jq -r '.[] | "\(.name)\t\(.metadata.container.tags[])"'

  pull-latest:
    desc: "latest イメージを pull → pytest -q でスモークテスト"
    cmds:
      - docker pull ghcr.io/{{.GHCR_USER}}/{{.GHCR_REPO}}:latest
      - docker run --rm ghcr.io/{{.GHCR_USER}}/{{.GHCR_REPO}}:latest \
          pytest -q || { echo '❌ smoke test failed'; exit 1; }

  prune-obsolete:
    desc: "RETAIN_DAYS を越えたタグを自動削除"
    summary: |
      GitHub REST v3 で日付フィルタ → 各タグを delete。CI から週1実行推奨。
    cmds:
      - |
        readarray -t IDS < <(gh api -H "Accept: application/vnd.github+json" \
          /users/{{.GHCR_USER}}/packages/container/{{.GHCR_REPO}}/versions \
          | jq -r --argjson keep {{.RETAIN_DAYS}} \
              '.[] | select((now - (.created_at|fromdate)) > ($keep*86400)) | .id')
        for id in "${IDS[@]}"; do
          echo "🗑  delete id $id"
          gh api --method DELETE \
            /user/packages/container/{{.GHCR_REPO}}/versions/"$id"
        done 