---
version: "3"

includes:
  flow: ./flow.yml      # validate / pipeline-local など
  core: ./core.yml      # COUNT=12 など共通変数

tasks:
  #──────────────────────────────────────────────
  # ① 変更ファイルをコミット ＋ プッシュ
  #──────────────────────────────────────────────
  commit-push:
    desc: "git pull --rebase → add → commit → push"
    cmds:
      - |
        # 1. 変更をステージしてコミット（変更が無ければスキップ）
        git add -A
        git commit -m "task split + COUNT=12 pipeline" || echo "No changes to commit"

        # 2. 最新 main をリベース
        git pull --rebase origin main || {
          echo "⚠️  Rebase で衝突しました。解決後 → git add <files> && git rebase --continue"; exit 1; }

        # 3. プッシュ
        git push
        echo "✅  push 完了"

  #──────────────────────────────────────────────
  # ② GitHub Actions の validate-and-test が終わるまで待つ
  #    gh CLI が必要（brew install gh）
  #──────────────────────────────────────────────
  ci:wait:
    deps: [commit-push]
    desc: "wait for CI validate-and-test to turn green"
    cmds:
      - |
        # Ensure GitHub CLI is available
        if ! command -v gh >/dev/null 2>&1; then
          echo "🔧 Installing GitHub CLI via Homebrew …"
          brew install gh || { echo "❌ Failed to install gh"; exit 1; }
        fi

        WF="validate-and-test"
        SHA=$(git rev-parse HEAD)
        echo "⏳ waiting for $WF / $SHA"
        while :; do
          STATUS=$(gh run list -c "$WF" -b "$SHA" --json status -q '.[0].status')
          RESULT=$(gh run list -c "$WF" -b "$SHA" --json conclusion -q '.[0].conclusion')
          echo "… $STATUS / $RESULT"
          [ "$STATUS" = "completed" ] && break
          sleep 30
        done
        if [ "$RESULT" != "success" ]; then
          echo "❌ CI failed ($RESULT)"; exit 1
        fi
        echo "🎉 CI green!"

  #──────────────────────────────────────────────
  # ③ ローカル 12 並列パイプラインを実行（任意）
  #──────────────────────────────────────────────
  local-run:
    deps: [ci:wait]
    desc: "COUNT=12 で local pipeline (parallel run→pick)"
    cmds:
      - task flow:pipeline-local
      - echo "🚀 local parallel loop finished"

  #──────────────────────────────────────────────
  # ④ すべてワンコマンド
  #──────────────────────────────────────────────
  done:
    desc: "commit → push → CI wait → local parallel run"
    deps: [local-run]
    cmds:
      - echo "🌟  全工程完了！" 