---
version: "3"

includes:
  core: ./core.yml          # COUNT / WT_DIR など共通変数

tasks:
  #--------------------------------------------------#
  # 1) git add → commit → push     (名前修正)
  #    next:commit-push
  #--------------------------------------------------#
  commit-push:
    desc: "stage all → commit → push HEAD"
    cmds:
      - git add -A
      - |
          if git diff --cached --quiet; then
            echo "🟢 nothing to commit (skip commit)"
          else
            git commit -m "fix: green branch squash"
          fi
      - git push -u origin HEAD

  #--------------------------------------------------#
  # 2) CI 待機         (next:ci-wait はそのまま可)
  #--------------------------------------------------#
  ci-wait:
    desc: "wait until GitHub Actions on HEAD is green"
    vars:
      SHA: "$(git rev-parse HEAD)"
    cmds:
      - |
          while :; do
            STATUS=$(gh run list -c "{{.SHA}}" -b "{{.SHA}}" \
                     --json status   -q '.[0].status'     2>/dev/null || echo none)
            RESULT=$(gh run list -c "{{.SHA}}" -b "{{.SHA}}" \
                     --json conclusion -q '.[0].conclusion' 2>/dev/null || echo none)
            if [ "$STATUS" = none ];            then echo "🔄 run not found yet"; sleep 20; continue; fi
            if [ "$STATUS" != completed ];      then echo "⏳ CI $STATUS…";      sleep 20; continue; fi
            [ "$RESULT" = success ] && break || { echo "❌ CI $RESULT"; exit 1; }
          done
      - echo "✅ CI green!"

  #--------------------------------------------------#
  # 3) ワンショット連鎖 (名前修正)
  #    next:push-main   ← commit-push → ci-wait
  #--------------------------------------------------#
  push-main:
    desc: "commit-push & wait for CI green"
    deps: [commit-push, ci-wait]
    cmds:
      - echo "🎉  main branch is green!"

#-------------------------------------------------------------#
# alias: commit:push  (colon style)
#-------------------------------------------------------------#
"commit:push":
  desc: "stage-all → commit → push current branch (alias)"
  deps: [commit-push]
  cmds:
    - echo "✅ commit:push finished" 