---
version: "3"

includes:
  core: ./core.yml     # COUNT, WT_DIR, CURSOR_BIN, etc.
  tests: ./tests.yml   # pytest helpers for assertions

# 並列で Cursor エージェントを走らせテスト合格ブランチをマージするユーティリティ

tasks:
  run:
    desc: "Run {{.COUNT}} Cursor agents in parallel (yes-piped)"
    cmds:
      - mkdir -p {{.LOG_DIR}}
      - |
        for i in $(seq 1 {{.COUNT}}); do
          (
            cd {{.WT_DIR}}-${i}
            export CURSOR_SESSION_ID=task_${i}
            yes | {{.CURSOR_BIN}} agent run {{.CFG}} \
              2>&1 | sed "s/^/[c${i}] /" \
              > {{.LOG_DIR}}/run_${i}.log &
          )
        done
        wait
      - echo "🚀  All agents finished; see logs in {{.LOG_DIR}}"

  pick:
    desc: "Squash-merge first green branch into main and clean worktree"
    cmds:
      - |
          ROOT_DIR="$(pwd)"
          for i in $(seq 1 {{.COUNT}}); do
            WT_PATH="{{.WT_DIR}}-${i}"
            cd "$WT_PATH"
            [ -f .venv/bin/activate ] && source .venv/bin/activate || true
            if pytest -q; then
              echo "✅  ai-task-${i} PASSED — merging into main in root repo"
              BRANCH="ai-task-${i}"
              cd "$ROOT_DIR"
              git checkout main
              git merge --squash "$BRANCH"
              git commit -m "merge(auto): $BRANCH" || echo "Nothing to commit"
              git worktree remove --force "$WT_PATH"
              git branch -D "$BRANCH" || true
              exit 0
            fi
            [ -n "$VIRTUAL_ENV" ] && deactivate || true
            cd "$ROOT_DIR" >/dev/null
          done
          echo "❌  No branch passed tests" && exit 1 