---
version: "3"

includes:
  core: ./core.yml
  venv: ./venv.yml
  debug: ./debug.yml
  flow: ./flow.yml

vars:
  COUNT: 12

tasks:
  shared:ensure:
    desc: "create shared venv if missing"
    status:
      - test -d {{.SHARED_VENV}}
    cmds:
      - task venv:create-shared

  agents:restart-12:
    desc: "restart cursor agents to match COUNT={{.COUNT}}"
    deps: [shared:ensure]
    cmds:
      - task debug:restart

  pipeline:12:
    desc: "validate & {{.COUNT}}-parallel run → pick"
    deps: [agents:restart-12]
    cmds:
      - task flow:pipeline:local
      - echo "🎉 {{.COUNT}} 並列パイプライン完了"

  push:all:
    desc: "pipeline:12 が緑なら commit & push"
    deps: [pipeline:12]
    cmds:
      - |
        git add -A
        git commit -m "run12: shared venv + COUNT=12 parallel loop" || echo "(no changes)"
        git push
        echo "🚀  pushed with COUNT={{.COUNT}}" 