# tasks/update_readme_and_pr.yaml
# yamllint disable rule:line-length
---
- task: update_readme_and_open_pr
  goal: |
    1. README.md に "Taskfile の検証フロー" セクションを追加し、
       `task validate:validate-and-test` の使い方を記載する。
    2. 追加後に `task validate:validate-and-test` を実行して緑を確認。
    3. ブランチ docs/task-validate を切り、コミット → プッシュ。
    4. gh CLI で Pull Request を自動生成（タイトル: docs: usage of validate task）。
  files:
    - path: README.md
      insert_after: "^## Development setup"
      content: |
        ## Taskfileの検証フロー

        分割した Taskfile が壊れていないかを一括で確認するには、以下を実行します。

        ```bash
        task validate:validate-and-test
        ```

        このコマンドは
        1. Taskfile 一覧表示
        2. YAML Lint
        3. ドライラン
        4. pytest
        をまとめて実行します。
  commands:
    # 1. 検証フローを回す
    - run: "task validate:validate-and-test"
    # 2. Git 操作
    - run: "git switch -c docs/task-validate || git switch docs/task-validate"
    - run: "git add README.md"
    - run: "git commit -m 'docs: add usage of validate task'"
    - run: "git push -u origin HEAD"
    # 3. PR 作成（gh CLI がセットアップ済み前提）
    - run: >-
        gh pr create --title "docs: usage of validate task" --body "Add README section for validate-and-test flow." --fill
