# yamllint disable rule:line-length
---
version: "3"

tasks:
  # ❶ 生成パッチを適用したあとの検証フローをワンコマンド化
  validate-and-test:
    desc: >
      Validate split Taskfiles, lint YAML, dry-run tasks, then run pytest
    cmds:
      - task --list                      # タスクが読めるか
      - yamllint tasks/                  # YAML 構文チェック
      - task --dry validate:commit-task-split      # タスク定義だけドライラン
      - |
        if ! command -v pytest >/dev/null 2>&1; then
          echo "⚙️  Installing pytest ..."
          python -m pip install --quiet pytest || exit 1
        fi
      - |
        echo "⚙️  Ensuring distutils (setuptools<69) ..."
        python -m pip install --quiet 'setuptools<69' || exit 1
      - pytest -q                        # テスト実行
    silent: false

  # ❷ ブランチ作成 → コミット → プッシュまで自動
  commit-task-split:
    desc: Commit modular Taskfiles and push to remote
    deps: [validate-and-test]
    cmds:
      - |
        git checkout -b refactor/task-split || \
          git checkout refactor/task-split
      - git add tasks/*.yml Taskfile.yml
      - |
        git commit -m "chore: split Taskfile into modular YAMLs" || \
          echo "Nothing to commit"
      - git push -u origin HEAD
    silent: false
