---
version: "3"

tasks:
  create-shared:
    desc: "create shared Python virtual environment and install current project"
    cmds:
      - |
        if [ ! -d {{.SHARED_VENV}} ]; then
          python -m venv {{.SHARED_VENV}}
        fi
      - |
        source {{.SHARED_VENV}}/bin/activate
        pip install -U pip setuptools --quiet
        pip install -e . --quiet
        deactivate

  # legacy alias
  venv:
    deps: [create-shared]
    cmds: [echo "(alias) shared venv ensured"]
