version: '3.8'

services:
  kakeru:
    image: ghcr.io/yusaku0324/kakeru:latest
    container_name: kakeru
    volumes:
      - ./profiles:/app/profiles
      - ./queue:/app/queue
      - ./debug:/app/debug
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Tokyo
    restart: unless-stopped
    command: python -m bot.main

  # 定期実行用のサービス例
  scheduler:
    image: ghcr.io/yusaku0324/kakeru:latest
    container_name: kakeru-scheduler
    volumes:
      - ./profiles:/app/profiles
      - ./queue:/app/queue
      - ./debug:/app/debug
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Tokyo
    restart: unless-stopped
    command: python -m bot.scheduler
