name: Claude Code Max Fixed
on:
  workflow_dispatch:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  claude-respond:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude')
    steps:
      - uses: actions/checkout@v4

      - name: Process Claude Request
        id: claude
        run: |
          # Extract request from comment or issue
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            REQUEST="${{ github.event.comment.body }}"
          else
            REQUEST="${{ github.event.issue.body }}"
          fi
          
          # Remove @claude mention and clean up
          REQUEST=$(echo "$REQUEST" | sed 's/@claude//g' | tr '\n' ' ')
          
          # Call Claude API
          RESPONSE=$(curl -s -X POST \
            -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" \
            -H "content-type: application/json" \
            https://api.anthropic.com/v1/messages \
            -d "{
              \"model\": \"claude-3-haiku-20240307\",
              \"max_tokens\": 500,
              \"messages\": [{\"role\": \"user\", \"content\": \"$REQUEST\"}]
            }" | jq -r '.content[0].text // "Error calling Claude API"')
          
          # Save response for next step
          echo "CLAUDE_RESPONSE<<EOF" >> $GITHUB_OUTPUT
          echo "$RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment Response
        uses: actions/github-script@v7
        with:
          script: |
            const response = `${{ steps.claude.outputs.CLAUDE_RESPONSE }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### Claude Response 🤖\n\n${response}\n\n---\n_Powered by Claude API_`
            });