name: Convert Markdown Draft to Queue

on:
  schedule:
    # 毎日01:00 JST (16:00 UTC)に実行
    - cron: '0 16 * * *'
  workflow_dispatch:
    # 手動実行も可能

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Convert Markdown to Queue
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python bot/md2queue.py
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add queue/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate queue from markdown draft" && git push)
