name: Nightly Figma Render

on:
  schedule:
    # Run at 2:00 JST (17:00 UTC)
    - cron: '0 17 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  render:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      
      - name: Run patch and render
        env:
          FIGMA_API_KEY: ${{ secrets.FIGMA_API_KEY }}
          FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}
          FIGMA_NODE_ID: ${{ secrets.FIGMA_NODE_ID }}
        run: |
          python bot/patch_and_render.py
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT_FOR_DEVIN }}
          commit-message: "Update queue with rendered PNG URLs"
          title: "Nightly Figma Render - ${{ github.run_number }}"
          body: |
            This PR updates the queue files with rendered PNG URLs from Figma.
            
            Generated by the nightly workflow run #${{ github.run_number }}
          branch: figma-render-${{ github.run_number }}
          delete-branch: true
