name: Nightly Figma Render

on:
  schedule:
    # Run at 2:00 JST (17:00 UTC)
    - cron: '0 17 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      
      - name: Run patch and render
        env:
          FIGMA_API_KEY: ${{ secrets.FIGMA_API_KEY }}
          FIGMA_FILE_ID: ${{ secrets.FIGMA_FILE_ID }}
          FIGMA_NODE_ID: ${{ secrets.FIGMA_NODE_ID }}
        run: |
          python bot/patch_and_render.py
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Commit and Push Changes
        run: |
          # Check if there are changes to commit
          if git diff --exit-code --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Create a new branch
          git checkout -b figma-render-${{ github.run_number }}
          
          # Add and commit changes
          git add queue/
          git commit -m "Update queue with rendered PNG URLs"
          
          # Push changes
          git push origin figma-render-${{ github.run_number }}
          
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create PR using GitHub CLI
          gh pr create \
            --title "Nightly Figma Render - ${{ github.run_number }}" \
            --body "This PR updates the queue files with rendered PNG URLs from Figma. Generated by the nightly workflow run #${{ github.run_number }}" \
            --base main \
            --head figma-render-${{ github.run_number }}
