name: Post to X

on:
  schedule:
    # 毎日09:30 JST (00:30 UTC)に実行
    - cron: '30 0 * * *'
  workflow_dispatch:
    # 手動実行も可能
    inputs:
      stop_bot:
        description: 'メンテナンスモード（実行しない）'
        required: false
        default: 'false'
        type: boolean

env:
  STOP_BOT: ${{ github.event.inputs.stop_bot || 'false' }}

jobs:
  post:
    if: env.STOP_BOT != 'true'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Setup accounts configuration
        run: |
          mkdir -p kakeru/config secrets
          cat > kakeru/config/accounts.yaml << EOF
          # Kakeru X (Twitter) Accounts Configuration
          niijima:
            cookie: secrets/niijima.jar
          EOF
          
          # Setup cookie files from secrets
          echo '${{ secrets.X_NIIJIMA_COOKIES }}' | base64 -d > secrets/niijima.jar
      - name: Run post script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CI: "true"
        run: |
          python generate_recruit_posts.py
