name: Run Tests

on:
  push:
    branches: [ main, feat/*, devin/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg chromium-browser
      
      - name: Run tests
        run: |
          pytest -q tests/test_retry.py
          pytest -q tests/test_post_text.py::test_text_input
          pytest -q tests/test_video_generation.py
          pytest -q tests/test_cookie_load.py
        env:
          PYTHONPATH: ${{ github.workspace }}
      
      - name: Run test coverage
        run: |
          pytest --cov=utils --cov=services tests/
        env:
          PYTHONPATH: ${{ github.workspace }}
