name: Run Tests

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ ソース取得
      - uses: actions/checkout@v4

      # 2️⃣ Python セットアップ & pip キャッシュ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"           # ← 依存解決を高速化

      # 3️⃣ 依存インストール（開発依存込み）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools<70"   # provides the distutils shim on Python 3.12
          pip install -e .[dev]

      # 4️⃣ テスト + カバレッジ 84% 以上必須
      - name: Run tests with coverage
        run: |
          pytest bot/tests/ -v \
            --cov=bot \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-fail-under=84

      # 5️⃣ カバレッジ成果物をアップロード（失敗時も保存）
      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-files
          path: |
            .coverage
            coverage.xml
