name: Test Claude Code Simple
on:
  workflow_dispatch:

jobs:
  test-claude:
    runs-on: self-hosted
    steps:
      - name: Setup PATH
        run: |
          echo "Setting up PATH for Claude CLI..."
          echo "PATH=$PATH:/Users/yusaku/.npm-global/bin" >> $GITHUB_ENV
          
      - name: Check Claude CLI
        run: |
          echo "🤖 Testing Claude Code CLI..."
          echo "=========================="
          echo "PATH: $PATH"
          which claude || echo "Claude not found in PATH"
          /Users/yusaku/.npm-global/bin/claude --version
          echo ""
          echo "✅ Claude Code CLI is working!"
          
      - name: System Info
        run: |
          echo "📊 System Information:"
          echo "OS: $(uname -s)"
          echo "Architecture: $(uname -m)"
          echo "Hostname: $(hostname)"
          echo "User: $USER"
          
      - name: Test Claude Help
        run: |
          echo "📖 Claude CLI Help:"
          /Users/yusaku/.npm-global/bin/claude --help | head -20