name: Schedule Video Tweets for @cristianisraelv

on:
  schedule:
    # JST 08:05 (UTC 23:05 prev day)
    - cron: '5 23 * * *'
    # JST 09:32 (UTC 00:32)
    - cron: '32 0 * * *'
    # JST 12:08 (UTC 03:08)
    - cron: '8 3 * * *'
    # JST 13:35 (UTC 04:35)
    - cron: '35 4 * * *'
    # JST 15:02 (UTC 06:02)
    - cron: '2 6 * * *'
    # JST 17:07 (UTC 08:07)
    - cron: '7 8 * * *'
    # JST 19:03 (UTC 10:03)
    - cron: '3 10 * * *'
    # JST 20:31 (UTC 11:31)
    - cron: '31 11 * * *'
    # JST 22:06 (UTC 13:06)
    - cron: '6 13 * * *'
    # JST 23:33 (UTC 14:33)
    - cron: '33 14 * * *'
  workflow_dispatch: # Manual trigger

jobs:
  post_tweet_cristianisraelv:
    name: Post Tweet for @cristianisraelv
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install Chrome for undetected-chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create cookie file for @cristianisraelv
        env:
          # Ensure this Secret name matches what you have for cristianisraelv in GitHub Secrets
          TWITTER_ACCOUNT_COOKIES: ${{ secrets.CRISTIANISRAELV_TWITTER_COOKIES_JSON }} 
        run: |
          mkdir -p cookies
          echo "$TWITTER_ACCOUNT_COOKIES" > cookies/cristianisraelv_twitter_cookies.json
          echo "Cookie file created at cookies/cristianisraelv_twitter_cookies.json"
          echo "Cookie file content (first 50 chars): $(head -c 50 cookies/cristianisraelv_twitter_cookies.json)"

      - name: Run tweet script for @cristianisraelv
        env:
          USE_UC: "1"
        run: python post_video_tweet.py --account cristianisraelv --headless

      - name: Commit and push posted log for @cristianisraelv
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          LOG_FILE="logs/posted_video_tweets_cristianisraelv.log"
          git add "$LOG_FILE"
          if ! git diff --staged --quiet; then
            git commit -m "Update $LOG_FILE via GitHub Actions for @cristianisraelv"
            git push
          else
            echo "No changes to $LOG_FILE to commit."
          fi
        continue-on-error: true 