name: Update X Cookies

on:
  schedule:
    # 毎週月曜日の03:00 UTC (12:00 JST)に実行
    - cron: '0 3 * * 1'
  workflow_dispatch:
    # 手動実行も可能

jobs:
  update-cookies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Validate cookies
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          X_NIIJIMA_COOKIES: ${{ secrets.X_NIIJIMA_COOKIES }}
        run: |
          # Base64デコードしてクッキーファイルを作成
          echo $X_NIIJIMA_COOKIES | base64 -d > niijima_cookies.json
          
          # クッキーの検証のみを実行
          python update_cookies.py --all --validate --repo ${{ github.repository }}
          
      - name: Notify if cookies need update
        if: ${{ failure() }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'X Cookiesの更新が必要です',
              body: 'X Cookiesの有効期限が近づいているか、期限切れです。手動でログインして更新してください。'
            });
            console.log(`Issue created: ${issue.data.html_url}`);
